### ISSUE TITLE
뭐해먹지 페이지

### ISSUE THREAD

**Issue by seoyeonyoon** [ProjectInTheClass/Refrigerator#1]
블로그 링크?
있는 재료 기반으로 요리 추천?

정렬 방식 어떻게 할껀지

**Comment by MinSeobi** [comment]
뭐해먹지 페이지는 기존에 존재하는 반찬을 응용해서(재활용해서) 할 수 있는 요리를 나타내는 것으로 한다.
(ex. 장조림이 있으면 장조림 버터밥 추천)
요리에 필요한 부재료는 인식하지 않고 현재 존재하는 반찬만 인식하도록 한다.
만약 반찬이 하나도 없으면 기본 반찬을 만들 수 있는 방법을 제공한다.

**Comment by seoyeonyoon** [comment]
요리 사진 밑에 필요한 요리 재료 뜨게 하고, 없는 재료는 다른 색으로 표시
부재료는 요리 추천을 위해 인식되지는 않지만 재료 목록에는 뜨게 해야한다
