### ISSUE TITLE
각 화면 이슈 정리

### ISSUE THREAD

**Issue by seoyeonyoon** [ProjectInTheClass/Refrigerator#3]
#![default](https://cloud.githubusercontent.com/assets/24871715/22019102/62e25da2-dcf5-11e6-9203-e98a9516d383.jpg)

![20170117_202254](https://cloud.githubusercontent.com/assets/24871715/22138062/1ec917a8-df22-11e6-8381-29530c76b5d0.jpg)

**Comment by MinSeobi** [comment]
1. 뭐해먹지를 메인 화면으로 구성. 앱의 성격을 냉장고 관리 보다는, 유통기한이 임박했거나 해서 긴급하게 사용해야 하는 재료나 반찬을 가지고 만들 수 있는 앱을 만들기로 함.
2. 장바구니 탭 삭제.
3. 나눔장터의 존속 여부 결정해야함.
